#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: 5424026
#
Name     : R-beepr
Version  : 2.0
Release  : 2
URL      : https://ftp.osuosl.org/pub/cran//src/contrib/beepr_2.0.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran//src/contrib/beepr_2.0.tar.gz
Summary  : Easily Play Notification Sounds on any Platform
Group    : Development/Tools
License  : GPL-3.0
Requires: R-audio
BuildRequires : R-audio
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
make it easy to play notification sounds on whatever platform you are on.
    It is intended to be useful, for example, if you are running a long analysis
    in the background and want to know when it is ready.

%prep
%setup -q -n beepr

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1732148777

%install
export SOURCE_DATE_EPOCH=1732148777
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/beepr/DESCRIPTION
/usr/lib64/R/library/beepr/INDEX
/usr/lib64/R/library/beepr/Meta/Rd.rds
/usr/lib64/R/library/beepr/Meta/features.rds
/usr/lib64/R/library/beepr/Meta/hsearch.rds
/usr/lib64/R/library/beepr/Meta/links.rds
/usr/lib64/R/library/beepr/Meta/nsInfo.rds
/usr/lib64/R/library/beepr/Meta/package.rds
/usr/lib64/R/library/beepr/NAMESPACE
/usr/lib64/R/library/beepr/NEWS
/usr/lib64/R/library/beepr/R/beepr
/usr/lib64/R/library/beepr/R/beepr.rdb
/usr/lib64/R/library/beepr/R/beepr.rdx
/usr/lib64/R/library/beepr/help/AnIndex
/usr/lib64/R/library/beepr/help/aliases.rds
/usr/lib64/R/library/beepr/help/beepr.rdb
/usr/lib64/R/library/beepr/help/beepr.rdx
/usr/lib64/R/library/beepr/help/paths.rds
/usr/lib64/R/library/beepr/html/00Index.html
/usr/lib64/R/library/beepr/html/R.css
/usr/lib64/R/library/beepr/sounds/facebook.wav
/usr/lib64/R/library/beepr/sounds/microwave_ping_mono.wav
/usr/lib64/R/library/beepr/sounds/new_item.wav
/usr/lib64/R/library/beepr/sounds/ready_master.wav
/usr/lib64/R/library/beepr/sounds/shotgun.wav
/usr/lib64/R/library/beepr/sounds/smb_coin.wav
/usr/lib64/R/library/beepr/sounds/smb_stage_clear.wav
/usr/lib64/R/library/beepr/sounds/sword.wav
/usr/lib64/R/library/beepr/sounds/victory_fanfare_mono.wav
/usr/lib64/R/library/beepr/sounds/wilhelm.wav
/usr/lib64/R/library/beepr/sounds/work_complete.wav
/usr/lib64/R/library/beepr/tests/testthat.R
/usr/lib64/R/library/beepr/tests/testthat/test-beepr.R
